### ISSUE TITLE
Server-side: Seeds( recipes, families, users)

### ISSUE THREAD

**Issue by abenedetti27** [abenedetti27/recipe-rolodex#5]

**Comment by TwixmixyJanet** [comment]
Images for seed data:
![chicken_alfredo](https://github.com/abenedetti27/recipe-rolodex/assets/117195025/7b6ab1fa-3ad0-4cff-aa32-1c256f23a5f5)
![chicken_parmesan](https://github.com/abenedetti27/recipe-rolodex/assets/117195025/f19b9879-c8fd-448a-a896-0e39e31c94b4)
![chicken_tikka_masala](https://github.com/abenedetti27/recipe-rolodex/assets/117195025/4abe79c7-2f43-4615-87af-acc3626f6bf9)
![roast_beef](https://github.com/abenedetti27/recipe-rolodex/assets/117195025/36621a27-f49d-4db4-b2dd-b31768211721)
![spaghetti](https://github.com/abenedetti27/recipe-rolodex/assets/117195025/360b8d3c-3927-4889-819b-062629e20bee)
![vegetarian_stir_fry](https://github.com/abenedetti27/recipe-rolodex/assets/117195025/d7ca02dd-7afe-494c-b0e0-f06c9e62a996)
